# Generated by Django 2.2 on 2020-01-14 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta', '0002_auto_20200113_2145'),
        ('parcelamento', '0001_initial'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.PositiveIntegerField()),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.Categoria')),
                ('conta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='conta.Conta')),
                ('parcelamento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parcelamento.Parcelamento')),
            ],
        ),
    ]
