# Generated by Django 2.2 on 2020-01-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200126_0046'),
        ('receita_gasto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitagasto',
            name='usuario_matricula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuario.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receitagasto',
            name='conta_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conta.Conta'),
            preserve_default=False,
        ),
    ]
