# Generated by Django 2.2 on 2020-01-14 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_final', models.PositiveIntegerField()),
                ('cartao_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartao.Cartao')),
            ],
        ),
    ]
