# Generated by Django 2.2 on 2020-01-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.IntegerField()),
                ('somatorio', models.BooleanField()),
                ('tipo_conta_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipo_conta.TipoConta')),
            ],
        ),
    ]
