# Generated by Django 2.2 on 2020-01-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='data_cadastro',
            field=models.PositiveIntegerField(),
        ),
    ]
